### ISSUE TITLE
The URL provided is not built in a proper way: ${URL} 

### ISSUE THREAD

**Issue by westorm-alt** [edoardottt/cariddi#76]
```The URL provided is not built in a proper way: www.edoardoottavianelli.it```

I tried with the sample I saw on the video but still not working. I have all packages and libraries, GO included so I don't know why is not working. Have a nice Sunday!

*EDIT
It works using __powershell__ but not terminal.
Also some endpoints don't work, maybe because they are private e.g.: ```https://api.nike.com```

**Comment by westorm-alt** [comment]
Goodmorning! 
Sorry if I wasn't specific about it, but yes by terminal we are refering cmd.exe. I'm running Win10 with the latest GO version.

For the second issue, is normal, that endpoint if you browse normally without any route it will give you DNS failure. Is an API used for Nike, with specific routes and specific parameters. I was wondering around if I could find anything. (I did found by myself, but public endpoints. I'm searching for the hidden ones).

Thank you for your availability.

**Comment by edoardottt** [comment]
For the first issue I will try to explore more if I can find something.

For the second instead, well that's why cariddi can't find anything. A crawler/spider extracts from the web page all the URLs it can find, then it will recursively tries to follow them. If you provide a web page without any link, of course cariddi can't find links.

**Comment by edoardottt** [comment]
Use Powershell.
